name: orangehrm-playwrightjs-automationframework
on:
workflow_dispatch:
jobs:
regression:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: 24
-run: npm ci
-run: npx playwright install --with-deps
-name: Run All Environments
run: npm run regression
-name: Upload Reports
if: always()
uses: actions/upload-artifact@v4
with:
name: playwright-report
path: playwright-report/